version: "3.8"

networks:
  korbojoyecommerce:
    driver: bridge
  korbojoyadmin:
    driver: bridge
  korbojoymembers:
    driver: bridge

services:
  ecommerce:
    build:
      context: ./korbojoyecommerce
      dockerfile: Dockerfile_APP
    image: korbojoyecommerce
    ports:
      - "8050:3000"
    networks:
      - korbojoyecommerce
  korbojoyadmin:
    build:
      context: ./korbojoyadmin
      dockerfile: Dockerfile_Admin
    image: korbojoyadmin
    ports:
      - "8051:3000"
    networks:
      - korbojoyadmin
  korbojoymembers:
    build:
      context: ./korbojoymembers
      dockerfile: Dockerfile_Member
    image: korbojoymembers
    ports:
      - "8052:3000"
    networks:
      - korbojoymembers
